package Entities;
// Generated 08-jul-2017 11:16:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private String fbId;
     private String name;
     private Set blueprints = new HashSet(0);
     private Set scores = new HashSet(0);
     private Set comments = new HashSet(0);
     private Set mockups = new HashSet(0);

    public User() {
    }

	
    public User(String fbId, String name) {
        this.fbId = fbId;
        this.name = name;
    }
    public User(String fbId, String name, Set blueprints, Set scores, Set comments, Set mockups) {
       this.fbId = fbId;
       this.name = name;
       this.blueprints = blueprints;
       this.scores = scores;
       this.comments = comments;
       this.mockups = mockups;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getFbId() {
        return this.fbId;
    }
    
    public void setFbId(String fbId) {
        this.fbId = fbId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getBlueprints() {
        return this.blueprints;
    }
    
    public void setBlueprints(Set blueprints) {
        this.blueprints = blueprints;
    }
    public Set getScores() {
        return this.scores;
    }
    
    public void setScores(Set scores) {
        this.scores = scores;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }
    public Set getMockups() {
        return this.mockups;
    }
    
    public void setMockups(Set mockups) {
        this.mockups = mockups;
    }




}


